#!/usr/bin/env python3
# SPDX-License-Identifier: MPL-2.0
"""Assemble this toolkit's mods into a payload any bench can run.

The payload is the whole of what a bench needs and the only thing it is given:
an opaque directory holding a manifest, the shared objects to preload, and the
assets to install. The bench reads the manifest; it never reads this repository.

Panel geometry is derived from the module headers rather than restated, so the
one map the hook uses in C is also the one the payload declares. A control that
moved in a header moves in the payload on the next build, and a button that
would have missed by a pixel cannot silently appear.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import shutil
import subprocess
import sys


REPOSITORY = pathlib.Path(__file__).resolve().parents[2]
FIRMWARE = "1.19"

# Where the hook listens, mirroring emulator_apply_touch in rx3_core_hook.c.
# tests/test_payload_geometry.py reads the hook's own bands and fails on drift.
TAB_ROW = 388            # the feature tabs occupy y 363..413
MODE_ROW = 458           # the stock mode row occupies y 433..483
CONTROL_ROW = 540        # the panel control row occupies y 521..560
SLOTS = (1135, 1225)     # slot 0 spans x 1090..1179, slot 1 spans x 1181..1270
DECK_STRIDE = 640        # the hook reads the deck straight off x >= 640
DECKS = 2

LOG_FILE = "tmp/rx3-stems.log"
READY_FILE = "tmp/rx3-performance.ready"
PRIVATE_DIR = "root/pdj"

# NS_GetImageInfoByID: movw r3,#0x15cc -> movw r3,#0x1603. The same guarded
# pre-launch rewrite core/module.sh registers on a device.
IMAGE_TABLE_PATCH = (1874220, "cc3501e3", "033601e3", "image-table")

ASSETS = (
    "key-selected",
    "stems-selected",
    "none-selected",
    "status-none-selected",
)

# Which modules each variant turns on, and the environment that does it.
VARIANTS: dict[str, dict[str, str]] = {
    "keyshift": {"RX3_KEYSHIFT": "1", "RX3_EMULATOR_PANEL": "1"},
    "stems": {"RX3_STEMS_DIR": "/media/usb/RX3_STEMS", "RX3_EMULATOR_PANEL": "2"},
    "all": {
        "RX3_KEYSHIFT": "1",
        "RX3_STEMS_DIR": "/media/usb/RX3_STEMS",
        "RX3_EMULATOR_PANEL": "1",
    },
}
# Panels a variant installs, as (id, name, module directory holding its header).
PANELS: dict[str, tuple[tuple[int, str, str], ...]] = {
    "keyshift": ((1, "KEY", "keyshift"),),
    "stems": ((2, "STEMS", "stems"),),
    "all": ((1, "KEY", "keyshift"), (2, "STEMS", "stems")),
}
CONTROL_LABELS: dict[int, tuple[str, ...]] = {
    1: ("KEY -", "KEY 0", "KEY +"),
    2: ("INSTRUMENTAL", "VOCAL"),
}


class PayloadBuildError(Exception):
    """The payload cannot be assembled from this working tree."""


def panel_columns(module: str) -> list[tuple[int, int]]:
    """Read one module's control columns straight out of its panel header."""
    header = next(
        (REPOSITORY / "mod/modules" / module / FIRMWARE).glob("*_panel.h"), None
    )
    if header is None:
        raise PayloadBuildError(f"module {module!r} has no panel header")
    source = header.read_text()
    columns = {}
    for edge in ("lefts", "rights"):
        match = re.search(rf"_panel_{edge}\[\d+\] = \{{([^}}]*)\}}", source)
        if match is None:
            raise PayloadBuildError(f"{header.name} declares no {edge} array")
        columns[edge] = [int(value) for value in match.group(1).split(",")]
    if len(columns["lefts"]) != len(columns["rights"]):
        raise PayloadBuildError(f"{header.name}: column arrays differ in length")
    return list(zip(columns["lefts"], columns["rights"]))


def quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def manifest(variant: str, version: str) -> str:
    lines = [
        "# Generated by tools/rx3_payload/cli.py -- do not edit.",
        "",
        "[payload]",
        f"name = {quote(f'rx3-toolkit-{variant}')}",
        f"version = {quote(version)}",
        f"description = {quote(f'XDJ-RX3 toolkit mods ({variant}) for firmware {FIRMWARE}')}",
        "",
        "[[preload]]",
        'file = "lib/librx3_core.so"',
        f'install = "{PRIVATE_DIR}/librx3_core.so"',
        "",
    ]
    for asset in ASSETS:
        lines += [
            "[[asset]]",
            f'file = "assets/{asset}.rgb565"',
            f'install = "{PRIVATE_DIR}/rx3-{asset}.rgb565"',
            "",
        ]
    lines.append("[env]")
    for name, value in sorted(VARIANTS[variant].items()):
        lines.append(f"{name} = {quote(value)}")
    offset, stock, patched, label = IMAGE_TABLE_PATCH
    lines += [
        "",
        "[[patch]]",
        f"offset = {offset}",
        f"stock = {quote(stock)}",
        f"patched = {quote(patched)}",
        f"label = {quote(label)}",
        "",
        "[screen]",
        f"tab_row = {TAB_ROW}",
        f"mode_row = {MODE_ROW}",
        f"control_row = {CONTROL_ROW}",
        f"slots = [{', '.join(str(column) for column in SLOTS)}]",
        f"deck_stride = {DECK_STRIDE}",
        f"decks = {DECKS}",
        "",
        "[[mode]]",
        'label = "STATUS"',
        "slot = 0",
        "",
        "[[mode]]",
        'label = "BEAT FX"',
        "slot = 1",
        "",
    ]
    for slot, (identifier, name, module) in enumerate(PANELS[variant]):
        columns = panel_columns(module)
        labels = CONTROL_LABELS[identifier]
        if len(labels) != len(columns):
            raise PayloadBuildError(
                f"panel {name}: {len(labels)} labels for {len(columns)} columns"
            )
        lines += ["[[panel]]", f"id = {identifier}", f"name = {quote(name)}",
                  f"slot = {slot}", "controls = ["]
        for label, (left, right) in zip(labels, columns):
            lines.append(
                f"    {{ label = {quote(label)}, left = {left}, right = {right} }},"
            )
        lines += ["]", ""]
    lines += [
        "[checks]",
        f"ready_file = {quote(READY_FILE)}",
        f"log_file = {quote(LOG_FILE)}",
        "log_contains = [",
        '    "RX3 performance hook active",',
        '    "extended private KEY/STEMS image table installed",',
        '    "emulator virtual touch channel ready",',
        "]",
        # Either the hook says it drew, or its own counter is non-zero. Kept as
        # two alternatives because that is what the check has always accepted.
        "log_matches = [",
        r'    "emulator custom tab rendered|^probe custom tab draws\\s*=\\s*[1-9]",',
        r'    "emulator custom PAD rendered|^probe custom PAD draws\\s*=\\s*[1-9]",',
        "]",
        "",
    ]
    return "\n".join(lines)


def build(variant: str, output: pathlib.Path, version: str) -> pathlib.Path:
    if variant not in VARIANTS:
        raise PayloadBuildError(
            f"unknown variant {variant!r} (known: {', '.join(sorted(VARIANTS))})"
        )
    hook = REPOSITORY / "build/librx3_core_payload.so"
    if not hook.is_file():
        subprocess.run(["make", "payload-hook"], cwd=REPOSITORY, check=True)
    if not hook.is_file():
        raise PayloadBuildError("make payload-hook did not produce the hook")

    root = output / variant
    if root.exists():
        shutil.rmtree(root)
    (root / "lib").mkdir(parents=True)
    (root / "assets").mkdir(parents=True)
    shutil.copy2(hook, root / "lib/librx3_core.so")
    source = REPOSITORY / "mod/modules/core" / FIRMWARE / "assets"
    for asset in ASSETS:
        origin = source / f"{asset}.rgb565"
        if not origin.is_file():
            raise PayloadBuildError(f"missing asset: {origin}")
        shutil.copy2(origin, root / "assets" / f"{asset}.rgb565")
    (root / "manifest.toml").write_text(manifest(variant, version), encoding="utf-8")
    return root


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--variant", default="all", choices=sorted(VARIANTS),
        help="which modules the payload turns on",
    )
    parser.add_argument(
        "--output", type=pathlib.Path, default=REPOSITORY / "build/payload",
    )
    parser.add_argument("--version", default="0.0.0-dev")
    parser.add_argument(
        "--all-variants", action="store_true", help="build every variant",
    )
    arguments = parser.parse_args(argv)
    try:
        variants = sorted(VARIANTS) if arguments.all_variants else [arguments.variant]
        for variant in variants:
            root = build(variant, arguments.output.resolve(), arguments.version)
            print(root)
    except (PayloadBuildError, OSError, subprocess.CalledProcessError) as error:
        print(f"payload error: {error}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
